import json
import re
from typing import Any, Dict, List, Optional, Tuple

from app.core.logging_config import logger


class StructuredReviewParser:
    """Defensively extracts and parses structured review JSON from untrusted model outputs."""

    @staticmethod
    def _clean_json_candidate(candidate: str) -> str:
        """Removes common LLM JSON syntax quirks such as trailing commas and unescaped line breaks."""
        # Strip trailing commas before closing braces or brackets
        cleaned = re.sub(r",\s*([}\]])", r"\1", candidate)
        return cleaned

    def parse(self, raw_text: str) -> Tuple[Dict[str, Any], str, List[str]]:
        """Extracts and parses JSON from raw LLM output.

        Returns:
            Tuple[Dict[str, Any], str, List[str]]:
                - parsed dictionary
                - extraction method name
                - list of parsing warnings if any
        """
        warnings: List[str] = []
        if not raw_text or not raw_text.strip():
            warnings.append("Model produced empty text output.")
            return {"summary": "No review output generated by the model.", "findings": []}, "empty_fallback", warnings

        cleaned_text = raw_text.strip()

        # Strategy 1: Direct JSON parsing
        try:
            data = json.loads(cleaned_text)
            if isinstance(data, dict):
                return data, "direct_json", warnings
            if isinstance(data, list):
                warnings.append("Model returned a JSON array of findings instead of a review object.")
                return {"summary": "Code review findings", "findings": data}, "array_adaptation", warnings
        except json.JSONDecodeError:
            pass

        # Strategy 2: Extract from markdown code fences (```json ... ``` or ``` ... ```)
        fence_pattern = re.compile(r"```(?:json)?\s*(\{[\s\S]*?\})\s*```", re.IGNORECASE)
        match = fence_pattern.search(cleaned_text)
        if match:
            candidate = match.group(1).strip()
            try:
                data = json.loads(candidate)
                if isinstance(data, dict):
                    return data, "markdown_fence", warnings
            except json.JSONDecodeError:
                # Try cleaning trailing commas
                try:
                    data = json.loads(self._clean_json_candidate(candidate))
                    if isinstance(data, dict):
                        warnings.append("Cleaned trailing commas in markdown JSON fence.")
                        return data, "markdown_fence_cleaned", warnings
                except json.JSONDecodeError:
                    pass

        # Strategy 3: Find outermost curly braces { ... }
        first_brace = cleaned_text.find("{")
        last_brace = cleaned_text.rfind("}")
        if first_brace != -1 and last_brace != -1 and last_brace > first_brace:
            candidate = cleaned_text[first_brace : last_brace + 1].strip()
            try:
                data = json.loads(candidate)
                if isinstance(data, dict):
                    warnings.append("Extracted JSON from surrounding conversational text.")
                    return data, "outer_braces", warnings
            except json.JSONDecodeError:
                try:
                    data = json.loads(self._clean_json_candidate(candidate))
                    if isinstance(data, dict):
                        warnings.append("Extracted and sanitized JSON from surrounding text.")
                        return data, "outer_braces_cleaned", warnings
                except json.JSONDecodeError as exc:
                    logger.warning(f"Failed to parse inner JSON candidate: {exc}")

        # Strategy 4: Fallback to raw text summary (Never crash)
        warnings.append("Model response did not contain valid structured JSON. Preserving raw response as review summary.")
        return {
            "summary": cleaned_text,
            "findings": [],
        }, "raw_text_fallback", warnings
