"""initial_schema

Revision ID: dad717408364
Revises: 
Create Date: 2026-09-22 11:52:43.718374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'dad717408364'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('github_user_id', sa.BigInteger(), nullable=False),
    sa.Column('github_login', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_login', name='uq_users_github_login'),
    sa.UniqueConstraint('github_user_id', name='uq_users_github_user_id')
    )
    op.create_index(op.f('ix_users_github_login'), 'users', ['github_login'], unique=False)
    op.create_index(op.f('ix_users_github_user_id'), 'users', ['github_user_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('repositories',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_login', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('html_url', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_repo_id', name='uq_repositories_github_repo_id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=False)
    op.create_index(op.f('ix_repositories_github_repo_id'), 'repositories', ['github_repo_id'], unique=False)
    op.create_index(op.f('ix_repositories_is_active'), 'repositories', ['is_active'], unique=False)
    op.create_index(op.f('ix_repositories_user_id'), 'repositories', ['user_id'], unique=False)
    op.create_table('commits',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('repository_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('author_login', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('parent_sha', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'sha', name='uq_commits_repository_sha')
    )
    op.create_index('ix_commits_author_login', 'commits', ['author_login'], unique=False)
    op.create_index('ix_commits_committed_at', 'commits', ['committed_at'], unique=False)
    op.create_index('ix_commits_repository_id', 'commits', ['repository_id'], unique=False)
    op.create_index('ix_commits_sha', 'commits', ['sha'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('repository_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('github_pr_id', sa.BigInteger(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('author_login', sa.String(length=255), nullable=False),
    sa.Column('source_branch', sa.String(length=255), nullable=False),
    sa.Column('target_branch', sa.String(length=255), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('base_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'github_pr_id', name='uq_pull_requests_repository_github_pr'),
    sa.UniqueConstraint('repository_id', 'pr_number', name='uq_pull_requests_repository_pr_number')
    )
    op.create_index('ix_pull_requests_author_login', 'pull_requests', ['author_login'], unique=False)
    op.create_index('ix_pull_requests_created_at', 'pull_requests', ['created_at'], unique=False)
    op.create_index('ix_pull_requests_head_sha', 'pull_requests', ['head_sha'], unique=False)
    op.create_index('ix_pull_requests_repository_id', 'pull_requests', ['repository_id'], unique=False)
    op.create_index('ix_pull_requests_status', 'pull_requests', ['status'], unique=False)
    op.create_index('ix_pull_requests_updated_at', 'pull_requests', ['updated_at'], unique=False)
    op.create_table('analyses',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('pull_request_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_created_at', 'analyses', ['created_at'], unique=False)
    op.create_index('ix_analyses_head_sha', 'analyses', ['head_sha'], unique=False)
    op.create_index('ix_analyses_pull_request_id', 'analyses', ['pull_request_id'], unique=False)
    op.create_index('ix_analyses_pull_request_id_created_at', 'analyses', ['pull_request_id', 'created_at'], unique=False)
    op.create_index('ix_analyses_status', 'analyses', ['status'], unique=False)
    op.create_table('commit_analyses',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('commit_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('overall_status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('implementation_notes', sa.String(), nullable=True),
    sa.Column('testing_notes', sa.String(), nullable=True),
    sa.Column('error_handling_notes', sa.String(), nullable=True),
    sa.Column('documentation_notes', sa.String(), nullable=True),
    sa.Column('placeholder_notes', sa.String(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commit_analyses_commit_id', 'commit_analyses', ['commit_id'], unique=False)
    op.create_index('ix_commit_analyses_created_at', 'commit_analyses', ['created_at'], unique=False)
    op.create_index('ix_commit_analyses_overall_status', 'commit_analyses', ['overall_status'], unique=False)
    op.create_index('ix_commit_analyses_status', 'commit_analyses', ['status'], unique=False)
    op.create_table('pull_request_commits',
    sa.Column('pull_request_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('commit_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('pull_request_id', 'commit_id')
    )
    op.create_index('ix_pull_request_commits_commit_id', 'pull_request_commits', ['commit_id'], unique=False)
    op.create_index('ix_pull_request_commits_pull_request_id', 'pull_request_commits', ['pull_request_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('analysis_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('raw_artifact_uri', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'fingerprint', name='uq_findings_analysis_fingerprint')
    )
    op.create_index('ix_findings_analysis_id', 'findings', ['analysis_id'], unique=False)
    op.create_index('ix_findings_category', 'findings', ['category'], unique=False)
    op.create_index('ix_findings_file_path', 'findings', ['file_path'], unique=False)
    op.create_index('ix_findings_fingerprint', 'findings', ['fingerprint'], unique=False)
    op.create_index('ix_findings_severity', 'findings', ['severity'], unique=False)
    op.create_index('ix_findings_source', 'findings', ['source'], unique=False)
    op.create_index('ix_findings_status', 'findings', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('analysis_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('review_body', sa.String(), nullable=True),
    sa.Column('github_review_id', sa.BigInteger(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', name='uq_reviews_analysis_id')
    )
    op.create_index('ix_reviews_analysis_id', 'reviews', ['analysis_id'], unique=False)
    op.create_index('ix_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('ix_reviews_published_at', 'reviews', ['published_at'], unique=False)
    op.create_index('ix_reviews_status', 'reviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_status', table_name='reviews')
    op.drop_index('ix_reviews_published_at', table_name='reviews')
    op.drop_index('ix_reviews_created_at', table_name='reviews')
    op.drop_index('ix_reviews_analysis_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_findings_status', table_name='findings')
    op.drop_index('ix_findings_source', table_name='findings')
    op.drop_index('ix_findings_severity', table_name='findings')
    op.drop_index('ix_findings_fingerprint', table_name='findings')
    op.drop_index('ix_findings_file_path', table_name='findings')
    op.drop_index('ix_findings_category', table_name='findings')
    op.drop_index('ix_findings_analysis_id', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_pull_request_commits_pull_request_id', table_name='pull_request_commits')
    op.drop_index('ix_pull_request_commits_commit_id', table_name='pull_request_commits')
    op.drop_table('pull_request_commits')
    op.drop_index('ix_commit_analyses_status', table_name='commit_analyses')
    op.drop_index('ix_commit_analyses_overall_status', table_name='commit_analyses')
    op.drop_index('ix_commit_analyses_created_at', table_name='commit_analyses')
    op.drop_index('ix_commit_analyses_commit_id', table_name='commit_analyses')
    op.drop_table('commit_analyses')
    op.drop_index('ix_analyses_status', table_name='analyses')
    op.drop_index('ix_analyses_pull_request_id_created_at', table_name='analyses')
    op.drop_index('ix_analyses_pull_request_id', table_name='analyses')
    op.drop_index('ix_analyses_head_sha', table_name='analyses')
    op.drop_index('ix_analyses_created_at', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index('ix_pull_requests_updated_at', table_name='pull_requests')
    op.drop_index('ix_pull_requests_status', table_name='pull_requests')
    op.drop_index('ix_pull_requests_repository_id', table_name='pull_requests')
    op.drop_index('ix_pull_requests_head_sha', table_name='pull_requests')
    op.drop_index('ix_pull_requests_created_at', table_name='pull_requests')
    op.drop_index('ix_pull_requests_author_login', table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index('ix_commits_sha', table_name='commits')
    op.drop_index('ix_commits_repository_id', table_name='commits')
    op.drop_index('ix_commits_committed_at', table_name='commits')
    op.drop_index('ix_commits_author_login', table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_repositories_user_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_is_active'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_github_repo_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_github_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_login'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
